# Generated by Django 4.0 on 2021-12-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'Desert'), ('v', 'Vegetarian'), ('m', 'Meat Lover'), ('g', 'Gluten Free')], default='d', max_length=20),
        ),
    ]
