# Generated by Django 4.0 on 2021-12-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog3', '0002_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Desert', 'D'), ('Vegetarian', 'V'), ('Meat Lover', 'M'), ('Gluten Free', 'G')], default='D', max_length=20),
        ),
    ]
