# Generated by Django 4.0 on 2021-12-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog3', '0007_alter_post_status_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog3.category'),
        ),
    ]
