# Generated by Django 4.0 on 2021-12-30 21:36

import blog3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog3', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog3.models.user_directory_path),
        ),
    ]
