# Generated by Django 4.0 on 2021-12-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog3', '0006_category_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Desert', 'D'), ('Vegetarian', 'V'), ('Meat Lover', 'M'), ('Gluten Free', 'G')], default='DESERT', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
