# Generated by Django 4.0.1 on 2022-01-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
    ]
