# Generated by Django 4.0.1 on 2022-01-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_branch_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='teacher'),
        ),
    ]
