# Generated by Django 4.0.1 on 2022-01-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_name_branch_title_alter_branch_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='profile.jpg', upload_to='commment')),
                ('content', models.TextField(max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
